# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque #KeyValue Secret
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2VybmFtZQ==
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29wYXNzd29yZA==